### ISSUE TITLE
3 Warning, 1 Error

### ISSUE THREAD

**Issue by jrmldesign-official** [BirajMainali/expr-hash-vue-router#6]
<img width="959" alt="image" src="https://github.com/BirajMainali/crypted-vue-route/assets/70363293/801dbe5c-a1f7-4328-96fe-a9ef23908c80">

Can you check if I did the right step by step process
1. npm init vite@latest crypted-vue-route --template vue
2. cd .\crypted-vue-route\
3. npm i crypted-vue-route
4. Then I've copied the code from the markdown
5. npm run dev

**Comment by BirajMainali** [comment]
Hi @jrmldesign-official , thank you for bringing up your concern. It appears that your project might not have been initialized with Vue Router, as the library has externalized it to allow for handling your own version of routing. 

Here's a step-by-step guide on customizing your Vue project and adding Vue Router:

https://router.vuejs.org/installation.html

**Comment by jrmldesign-official** [comment]
Hey @BirajMainali thank you so much! It works now

<img width="960" alt="image" src="https://github.com/BirajMainali/crypted-vue-route/assets/70363293/aae466bd-a736-4b76-a128-891c21ba9e2f">
